name: Cron Job for Job Data Processing

on:
  schedule:
    - cron: '0 6 * * *'  # This will run the job daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        RECRUITER_ID : ${{ secrets.RECRUITER_ID }}
      run: |
        python main.py

    - name: Post execution status
      run: echo "Job execution completed."
